name: Build & Deploy Site

on:
  push:
    branches: [ "main" ]
    paths:
      - "attachments/**"
      - "reports.json"
      - "index.html"
      - ".github/workflows/build-deploy.yml"
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate attachments index
        run: |
          mkdir -p attachments
          node -e "
            const fs = require('fs');
            const path = require('path');
            const dir = 'attachments';
            const files = fs.readdirSync(dir)
              .filter(f => f.endsWith('.csv'))
              .map(f => ({ name: f }));
            fs.writeFileSync(path.join(dir, 'index.json'), JSON.stringify(files, null, 2));
            console.log('✅ Generated attachments/index.json with', files.length, 'files.');
          "

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update attachments index"

  deploy:
    needs: build-index
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
      - id: deployment
        uses: actions/deploy-pages@v4
